### ISSUE TITLE
the property of step on rating are expected to be adding in the next time

### ISSUE THREAD

**Issue by ThinWonton** [techery/ProperRatingBar#7] opened 2015-10-30 02:47 UTC
as title what  i says.
thank you for your help.

**Comment by Den-Rimus** [comment] 2015-10-31 07:54
Do you mean ability to set some fractional number for rating, like 2.25?

**Comment by ThinWonton** [comment] 2015-11-03 08:06
yes

**Comment by haidaraM** [comment] 2016-01-09 13:44
It will be very nice to add step and allow float value for rating.

**Comment by Den-Rimus** [comment] 2016-04-24 10:04
Duplicate of #16 as seems

**Closed by Den-Rimus** 2016-04-24 10:04 UTC
Labels: duplicate
