### ISSUE TITLE
the first one can't disappear

### ISSUE THREAD

**Issue by fangood** [techery/ProperRatingBar#6] opened 2015-10-29 07:31 UTC

**Comment by Den-Rimus** [comment] 2015-10-29 13:24
I assume that you are appealing to the fact that one can't set rating '0' by clicking the element. Well, that's is by design. Zero rating can only be set from xml or programmatically.

I will close this for now, please write here more detailed scenario if I guessed wrong and this is not about zero rating.

**Closed by Den-Rimus** 2015-10-29 13:24 UTC
